language: node_js

before_install:
  - "export DISPLAY=:99.0"

node_js:
  - '0.10'

before_script:
  - 'npm run lint'

after_script:
  - 'npm install coveralls@2.10.0 && cat ./coverage/lcov.info | coveralls'
